export const colors = {
  background: '#fdf9f1',
  error: '#ba1a1a',
  outline: '#74777f',
  primary: '#031f41',
  primaryContainer: '#1d3557',
  primaryFixed: '#d5e3ff',
  primaryFixedDim: '#b0c7f1',
  secondary: '#a0401c',
  secondaryContainer: '#fe875d',
  secondaryFixed: '#ffdbcf',
  surfaceContainer: '#f1ede5',
  surfaceContainerHigh: '#ece8e0',
  surfaceContainerHighest: '#e6e2da',
  surfaceContainerLow: '#f7f3eb',
  surfaceContainerLowest: '#ffffff',
  tertiary: '#002234',
  tertiaryFixed: '#c7e7ff',
  onSurface: '#1c1c17',
  onSurfaceVariant: '#44474e',
} as const
